version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python 3.12..."
      - sudo apt-get update && sudo apt-get install -y python3.12 python3.12-distutils
      - python3.12 --version
      - ln -sf /usr/bin/python3.12 /usr/bin/python
  build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
      - echo Packaging the Lambda function...
      - zip -r function.zip .
      - echo Uploading to S3...
      - aws s3 cp function.zip s3://deploy-github-repo/function.zip
      - echo Updating Lambda function...
      - aws lambda update-function-code --function-name get_and_process_iec_user_data --s3-bucket deploy-github-repo --s3-key function.zip
