version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping application"
      - zip -r lambda_function.zip .
artifacts:
  files:
    - lambda_function.zip
